version: "3.8"
services: 
  server: 
    container_name: server
    build: 
      context: ./server
      dockerfile: ./Dockerfile.dev
    ports: 
      - 3001:3001
    volumes: 
      - ./server/src:/home/nodeUser/app/src:rw
      - ./server/logs:/home/nodeUser/app/logs:rw
    depends_on: 
      - redis
      - mongodb
    env_file: "./server/.env"
    command: |
      sh -c "npm run test:watch"
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    # This one will save a snapshot of the DB every 20 seconds if at least 1 write operation was performe
    command: redis-server --save 20 1 --loglevel warning
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: gymDo
    ports:
      - 27017:27017
  