version: "3.8"
services: 
  server: 
    container_name: server
    build: 
      context: ./server
      dockerfile: ./Dockerfile.dev
    ports: 
      - 3001:3001
    volumes: 
      - ./server/src:/home/nodeUser/app/src:rw
    depends_on: 
      - redis
      - mongodb
    environment:
      - PORT=3001
      - JWT_SIGNING_KEY=KalxrIEUI44sozcCMHtItVpmelSn3vKd
      - REFRESH_TOKEN_KEY=?`?p#|+i%S4#Wv*aw3M"@lKSWp?tb0
      - MONGO_ATLAS_DB_NAME=gymDo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: |
      sh -c "npm run test"
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    # This one will save a snapshot of the DB every 20 seconds if at least 1 write operation was performe
    command: redis-server --save 20 1 --loglevel warning
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: gymDo
    ports:
      - 27018:27017
  