version: "3.8"
services: 
  server: 
    container_name: server
    build: 
      context: ./server
      dockerfile: ./Dockerfile.spec
    ports: 
      - 4000:3000
    depends_on: 
      - redis
      - mongodb
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    # This one will save a snapshot of the DB every 20 seconds if at least 1 write operation was performe
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
  